name: Backup Firestore

on:
  schedule:
    - cron:  '0 4 * * 0'
  workflow_dispatch:

env:
  PROJECT_ID: never-have-i-ever-f7386
  BUCKET: gs://never-have-i-ever-f7386.appspot.com

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud
        with:
          service_account_key: ${{ secrets.GCP_EXPORT_ACTION_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET